### ISSUE TITLE
Serviço de camadas

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/api#50]
O serviço de camadas deverá receber arquivos geojson com estilo, para serem exibidos no mapa de armadilhas. O modelo:

- id
- visible: boolean
- title: string
- description: string
- properties: array(string)
- geojson: json
- tooltip: json, é usado para marcar se há e quais são os campos a serem exibidos no tooltip

**Comment by miguelpeixe** [comment]
Especificar modelo de dados

**Comment by miguelpeixe** [comment]
Como será feita a ordenação das camadas? Não está no modelo.

tooltipFields eu mudaria para fields, com um array de objetos:

```json
{
  "fields": [
    {
      "key": "propriedade",
      "label": "Propriedade"
    }
  ]
}

É importante o backend retornar também a lista de campos de propriedade do geojson, como não há modelagem a camada pode conter diferentes múltiplos campos.

**Comment by vgeorge** [comment]
Adicionei o campo `visible` e a `properties`, que vai guardar as propriedades das feições do GeoJSON fazendo um parse no momento de envio.

Sobre a ordenação, acho que faz mais sentido guardar em um serviço de configurações gerais da plataforma, que descrevo aqui: https://github.com/aetrapp/api/issues/53

**Comment by vgeorge** [comment]
@miguelpeixe Subi o serviço de layers, aqui está o modelo: https://github.com/aetrapp/api/blob/master/src/models/layers.model.js.

Ele já está calculando as propriedades presentes no GeoJSON, mas a ordenação depende ainda depende da #53.
